language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck doxygen graphviz lcov qt5-qmake qtbase5-dev 


before_script:
  - qmake -qt=qt5

script:
  - cppcheck --error-exitcode=1 --quiet .
  - make
  - make check

after_success:
  - make -C test coverage
