version: 1.0.{build}
build:
  verbosity: minimal
install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake mltranslator.pro
  - mingw32-make
artifacts:
  - path: release/mltranslator.exe
    name: Translator
